version: "3.9"

services:
  bot:
    build:
      context: .
    container_name: twitchannouncer
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
