version: "3.9"

services:
  bot:
    build:
      context: .
    container_name: twitchannouncer
    restart: always
    ports:
      - "8080:8080"  # Проброс порта для webhook
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
